### ISSUE TITLE
Week 1 of CPT Checklist

### ISSUE THREAD

**Issue by mmaxwu** [mmaxwu/reunion#1]
- [x] Brainstorm ideas
- [x] Settle on one idea
- [x] Choose a theme
- [x] Decide on the Specifics of the project
- [x] Add weather on the homepage
- [x] Make sure the weather table is live, not just static
- [ ] Create a live table that generates random numbers
- [ ] Create a live table that tracks the number of wildlife in the national parks
- [ ] Create a live table that checks if the restaurants in the national parks are open or closed
