### ISSUE TITLE
Checklist Week #4

### ISSUE THREAD

**Issue by JishnuS420** [mmaxwu/reunion#10]
**Everyone:**

- [x] Project Approval Presentation
- [x] Discuss about future plans; set checkpoints/goals throughout the weeks
- [x] Notes from Office Hours

**Individual Stuff:**
Max:
- [x] Individual Blog on the Project
- [x] Collegeboard 5.1 and 5.2 Notes Blog
- [x] Collegeboard MCQ Test 2 

Evan:
- [x] Individual Blog on the Project
- [x] Collegeboard 5.1 and 5.2 Notes Blog
- [x] Collegeboard MCQ Test 2

Jishnu: 
- [x] Individual Blog on the Project
- [x] Collegeboard 5.1 and 5.2 Notes Blog
- [x] Collegeboard MCQ Test 2

Alan: 
- [x] Individual Blog on the Project
- [x] Collegeboard 5.1 and 5.2 Notes Blog
- [x] Collegeboard MCQ Test 2

**Comment by JishnuS420** [comment]
Good job completing all the tasks this week, keep it up.
