### ISSUE TITLE
Week 2 of the CPT checklist

### ISSUE THREAD

**Issue by JishnuS420** [mmaxwu/reunion#6]
- [ ]  Fix the wildlife table
- [ ] Fix the headers and the navigation bar
- [ ] Add more Navigation tabs
