### ISSUE TITLE
Checklist Week #2

### ISSUE THREAD

**Issue by JishnuS420** [mmaxwu/reunion#7]
- [x] Change the theme 
- [x] Fix the navigation bar 
- [x] Change the Font color 
- [x] Start coding snake
- [x] Fix the issues
- [x] Research and look more into class and objects 
- [x] Organize the repository (change file names, remove unwanted items, e.t.c.)
- [x] Change the default html
- [x] Work on the hacks
- [x] Work on the CSS
